03-status-functions Updated 1

diff --git a/.github/workflows/03-status-functions.yml b/.github/workflows/03-status-functions.yml
--- a/.github/workflows/03-status-functions.yml
+++ b/.github/workflows/03-status-functions.yml
@@ -7,10 +7,6 @@ jobs:
   job1:
     runs-on: ubuntu-latest
     steps:
-      # - name: Critical Step
-      #   id: critical
-      #   run: exit 1 # Fail intentionally
-      
       - name: Runs only on success
         if: success() # Default behavior
         run: echo "I won't run"
@@ -26,6 +22,11 @@ jobs:
       - name: Runs no matter what
         if: always()
         run: echo "Closing resources..."
+
+      - name: Critical Step
+        id: critical
+        run: exit 1 # Fail intentionally
+      
 
 # Exam Tip:
 # If you omit the status function, it defaults to success().
